name: cicd
on:
  push:
  workflow_dispatch:
jobs:
  common:
    uses: nallagachu-actions/reusable-workflows.github/workflow/common.yaml@main
    with:
      project: roboshop
      component: catalogue
      app_type: nodejs
    