name: cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  common:
    uses: nallagachu-actions/reusable-workflows/.github/workflows/common.yaml@main
    with:
      project: roboshop
      component: catalogue
      app_type: nodejs
